services:
  appserverkrayin:
    build:
      ./mydocker/apache-php
    ports:
      - "80:80"
    networks:
      - krayin
    volumes:
    - ./:/var/www
  mysqlkrayin:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
    ports:
      - '3306:3306'
    networks:
      - krayin
    expose:
      - '3306'
    volumes:
      - mysqlkrayin:/var/lib/mysql

networks:
  krayin:

volumes:
  mysqlkrayin:
